language: r
env:
  global:
  - ENCRYPTION_LABEL=2628f5796ab9
  - COMMIT_AUTHOR_EMAIL=byronelenilson@gmail.com
  - CXX=g++-4.8
script:
- make all
after_success:
- bash ./deploy.sh
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_2628f5796ab9_key -iv $encrypted_2628f5796ab9_iv -in deploy_key.enc -out deploy_key -d

