addons:
  apt_packages:
    - pandoc
env:
  global:
  - ENCRYPTION_LABEL=cecc20951448
  - COMMIT_AUTHOR_EMAIL=byronelenilson@gmail.com
  - CXX=g++-4.8
script:
- yarn test
- yarn lint
- yarn docs:api
after_success:
- bash ./deploy.sh
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- openssl aes-256-cbc -K $encrypted_cecc20951448_key -iv $encrypted_cecc20951448_iv
  -in deploy_key.enc -out deploy_key -d

